name: Python check

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run linter
        # Run tox using the version of Python in `PATH`
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8","3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run test
        # Run tox using the version of Python in `PATH`
        run: make test

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8","3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run coverage
        # Run tox using the version of Python in `PATH`
        run: make coverage

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run docs
        # Run tox using the version of Python in `PATH`
        run: make docs

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run build
        # Run tox using the version of Python in `PATH`
        run: |
          make sdist-wheel
          make dist-wheel