name: Python check

on: [push]

env:
  PYTHON_VERSION: 3.11

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Init project
        run: make sync PYTHON_VERSION=$PYTHON_VERSION
      - name: Run linter
        run: make lint PYTHON_VERSION=$PYTHON_VERSION

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Init project
        run: make sync PYTHON_VERSION=$PYTHON_VERSION
      - name: Run test
        run: make test PYTHON_VERSION=$PYTHON_VERSION

  coverage:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Init project
        run: make sync PYTHON_VERSION=$PYTHON_VERSION
      - name: Run coverage
        run: make coverage PYTHON_VERSION=$PYTHON_VERSION

  docs:
    needs: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Init project
        run: make sync PYTHON_VERSION=$PYTHON_VERSION
      - name: Run docs
        run: make docs PYTHON_VERSION=$PYTHON_VERSION

  build:
    needs: docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Init project
        run: make sync PYTHON_VERSION=$PYTHON_VERSION
      - name: Run build
        run: make build PYTHON_VERSION=$PYTHON_VERSION